# Generated by Django 4.0.1 on 2022-04-11 18:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projetos', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='category',
            field=models.CharField(choices=[('Infraestrutura', 'Infraestrutura'), ('Software', 'Software'), ('Consultoria', 'Consultoria')], max_length=200, null=True),
        ),
    ]
