# Generated by Django 4.0.1 on 2022-02-11 16:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('clientes', '0008_post'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Post',
        ),
    ]
