# Generated by Django 4.0.1 on 2022-04-07 17:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('controle', '0003_alter_order_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='tags',
        ),
    ]
