# Generated by Django 4.0.1 on 2022-04-05 17:23

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Contrato',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('entidade', models.CharField(max_length=30)),
                ('contrato', models.CharField(max_length=100)),
                ('estado', models.CharField(choices=[('A', 'ATIVO'), ('F', 'FINALIZADO')], max_length=1)),
                ('numero', models.DecimalField(decimal_places=0, default=0, max_digits=4)),
                ('data_inicio', models.DateField(blank=True, null=True)),
                ('contato', models.CharField(max_length=30)),
                ('telefone', models.CharField(max_length=30)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('endereço', models.CharField(max_length=30)),
                ('descricao', models.CharField(max_length=100)),
                ('preco', models.DecimalField(decimal_places=2, default=0.0, max_digits=5)),
                ('prazo', models.DecimalField(decimal_places=0, default=0, max_digits=4)),
                ('detalhes', models.TextField(blank=True)),
                ('digitalizado', models.ImageField(blank=True, null=True, upload_to='clients_photos')),
            ],
        ),
    ]
